### ISSUE TITLE
coding with chrome no longer exist?

### ISSUE THREAD

**Issue by ghost** [lebestnoob/CWC-Bypass#6]
I cant find it anywhere and I rly need a working bypass for securly someone helppp

**Comment by lebestnoob** [comment]
Sorry about that. It seems it has been delisted as the app is no longer maintained. You could try downloading the CRX, extract it (it's just a zip), and add it as an unpacked extension by enabling developer mode in the chrome extensions menu (assuming there isn't a whitelist in the chrome policy). 

For reference, the id for the extension is `becloognjehhioodmnimnehjcibkloed`. You'd have to search online for a CRX archive. 

Keep in mind that this method will soon stop working as support for Chrome Apps will drop on June of 2025.
